# Confluential - Confluence CLI Workflow Helper
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

## What is this?

Confluential aims to tame authoring content for Confluence. This is specifically
created for authors who prefer to edit content directly in XML/XHTML _or_ in Markdown,
Asciidoc, Rst, or any other file format which can output to xhtml. 

## What does it do?

On it's own, nothing. These utilities make certain assumptions, the first of which is
that users of them know a thing or two about command line utilities.

## Assumptions

* You have a webdav path for your Confluence Wiki.
** This can be done with davfs2 in linux, or with the methods from https://confluence.atlassian.com/doc/configuring-a-webdav-client-for-confluence-148044.html for Windows or MacOS
+
NOTE: Windows is not supported by these utilities unless you can run `bash` scripts
** With linux, simply add the confluence URL to `/etc/fstab` with a mount point of `$HOME/confluence/dav`, such as 
+
[source]
....
https://confluence.yourconfluenceserver.com/plugins/servlet/confluence/default /home/$USER/confluence/dav davfs defaults,noauto,user 0 0`
....
+
IMPORTANT: the `davfs2` package must be installed for this mount to work. See `mount.davfs` for details on the mount
+
WARNING: $USER in the above must be replaced with the appropriate username(s)
* You have cloned this repository as `$HOME/confluence/local`
** All scripts here are meant to run from within `$CWD` of `$HOME/confluence/local`

## The Utilities

* `sync_global.sh` - Will symlink the source documents for a confluence tree to your local copy.
+
This assumes you are in a directory with has a `./Global/` subdirectory, and symlinks the confluence
+
source file in the appropriate subtree of `./Global`. Usage:
+
[source]
....
./sync_global.sh ~/confluence/dav/Global/Space/SubPage/SubPage.txt
....
* `cpublish.sh` - Publish files to Confluence.
+
This is the one script I generally symlink in `~/bin`, so it's in my path and can be run from anywhere. Example usage:
+
[source]
....
cpublish.sh ~/confluence/local/Global/Space/SubSpace/SubPage/SubPage.txt
....
* `link_dav.sh` - For linking arbitrary files
