# Confluential - Confluence CLI Workflow Helper
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:

## What is this?

Confluential aims to tame authoring content for Confluence. This is specifically
created for authors who prefer to edit content directly in XML/XHTML _or_ in Markdown,
Asciidoc, Rst, or any other file format which can output to xhtml. 

## What does it do?

Nothing is automatic, nor magic. These utilities make certain assumptions, the first of which is
that users of them know a thing or two about command line utilities. The individual utilities
are responsible for copying files to a WEBDAV tree which must be available on your local host.

## Assumptions

* You have created a `$HOME/confluence` directory
** You have created a `$HOME/confluence/dav` directory
+
TIP: You can accomplish both of these at once with `mkdir -p $HOME/confluence/dav`
* You have a webdav path for your Confluence Wiki.
** This can be done with davfs2 in linux, or with the methods from https://confluence.atlassian.com/doc/configuring-a-webdav-client-for-confluence-148044.html for Windows or MacOS
+
CAUTION: Windows is not supported by these utilities unless you can run `bash` scripts
** With linux, simply add the confluence URL to `/etc/fstab` with a mount point of `$HOME/confluence/dav`, such as 
+
[source,txt]
----
https://confluence.yourconfluenceserver.com/plugins/servlet/confluence/default /home/$USER/confluence/dav davfs defaults,noauto,user 0 0
----
+
WARNING: $USER in the above must be replaced with the appropriate username(s)
+
IMPORTANT: the `davfs2` package must be installed for this mount to work. See `man mount.davfs` for details on the mount
* You have mounted the Confluence Wiki webdav mount at `$HOME/confluence/dav`
** In linux, after adding the above to your `/etc/fstab`, `mount ~/confluence/dav`
* You have cloned this repository as `$HOME/confluence/local`
+
[source,bash]
----
git clone https://github.com/bougyman/confluential ~/confluence/local
----
** All scripts here except for `to_adoc.sh` `cpublish.sh` and `tinywiki.sh` are meant to run from within `$CWD` of `$HOME/confluence/local`
* You have created `$HOME/confluence/local/Global` _after_ cloning this repository
+
[source,bash]
----
mkdir -vp ~/confluence/local/Global
----
** For editing your Personal space, `$HOME/confluence/local/Personal` must also exist
+
IMPORTANT: `$HOME/confluence/local/Personal` will publish to `$HOME/confluence/dav/Personal/~$USER`

TIP: Symlink `to_adoc.sh`, `cpublish.sh` and `tinywiki.sh` in your `$PATH` for easy usage

## The Utilities

* `sync_global.sh` - Will symlink the source documents for a confluence tree to your local copy.
+
This assumes you are in a directory with has a `./Global/` subdirectory (such as `~/confluence/local/`),
+
and symlinks the confluence source file in the appropriate subtree of `./Global`. Usage:
+
[source,bash]
----
./sync_global.sh ~/confluence/dav/Global/Space/SubPage
----
* `cpublish.sh` - Publish files to Confluence.
+
Assuming this is in your path, Example usage:
+
[source,bash]
----
cpublish.sh ~/confluence/local/Global/Space/SubSpace/SubPage/SubPage.xml
----
+
This will publish the xml document to `~/confluence/dav/Global/Space/SubSpace/SubPage/SubPage.txt`, which will then become a new version on your confluence wiki. The command will also output the path to the wiki page.
+
NOTE: The wiki will not be updated for ~ 10 seconds, depending on your davfs write delay (default for `davfs2` in linux is to wait 10 seconds to upload, in order to avoid uploading temporary/transient files to Confluence)
* `tidywiki.sh` - Turns the Confluence-saved "`.txt`" file into prettified xml. Assuming this is in your path, Usage:
+
[source,bash]
----
tidywiki.sh ~/confluence/local/Global/Space/Subspace/SubPage.txt
----
+
This will create `~/confluence/local/Global/Space/Subspace/SubPage.xml`
+
IMPORTANT: Requires `tidy`, an xml/xhtml prettifier, available on most platforms
* `to_adoc.sh` - A workflow which combines many of the above. Meant to be run from the local subspace
+
[source,bash]
----
% cd ~/confluence/local/Global/Space/Subspace/
% to_adoc.sh Subspace.txt
----
+
IMPORTANT: Both `tidywiki.sh` and `adoc_to_confluence.sh` (preferred) or `asciidoctor` must be in PATH for `to_adoc.sh`
* `link_dav.sh` - For linking arbitrary files

== Workflow

Ensure you have met all of the Assumptions, and can list files in the Confluence WEBDAV directory

[source,bash]
----
ls ~/confluence/dav/Global/
----

=== Editing Existing Pages

. Sync the space you wish to edit
+
[source,bash]
----
cd ~/confluence/local
./sync_global.sh ~/confluence/dav/Global/SomeSpace/SomeSubSpace/SomePage
----
. Convert the file to a cleaner format
+
[source,bash]
----
./tidywiki.sh ~/confluence/local/Global/SomeSpace/SomeSubSpace/SomePage/SomePage.txt
----
.. You can now edit `~/confluence/local/Global/SomeSpace/SomeSubSpace/SomePage/SomePage.xml`
. Publish The Edited file to Confluence
+
[source,bash]
----
cpublish.sh ~/confluence/local/Global/SomeSpace/SomeSubSpace/SomePage/SomePage.xml
----
.. cpublish will output the URL where you can view the published page

=== Creating New Pages
. Create the page directory in your local tree
+
[source,bash]
----
mkdir -p ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage
----
. Create the xhtml file with the content to publish
.. Regular xml, with a normal editor
+
[source,bash]
----
vim ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.xml
----
.. Asciidoc (Using confluence-converter or asciidoctor for conversion to xhtml)
+
[source,bash]
----
vim ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.adoc
adoc_to_confluence.sh ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.adoc
----
+
Uses the Atlassian offician converter, isolated in https://github.com/amdrake93/confluence-publisher OR
+
[source,bash]
----
asciidoctor -b xhtml5 -o ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.xml ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.adoc
----
+
WARNING: The asciidoctor xhtml5 backend will not format the xhtml as nicely as adoc_to_confluence.sh
+
.. Markdown (Using pandoc for conversion to xhtml)
+
[source,bash]
----
vim ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.md
pandoc -t html -o ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.xml ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.md
----
. Publish The file to Confluence
+
[source,bash]
----
cpublish.sh ~/confluence/local/Global/SomeSpace/SomeSubSpace/OtherPage/OtherPage.xml
----
.. cpublish will output the URL where you can view the new page

=== Asciidoc Helper
If you wish to edit in asciidoc, a helper script `to_adoc.sh` is supplied to facilitate this. It replaces
the above workflows with a complete import/edit/publish cycle.

==== Usage
[source,bash]
----
cd ~/confluence/local
./sync_global.sh ~/confluence/dav/Global/SomeSpace/SomeSubSpace/SomePage
cd ~/confluence/local/Global/SomeSpace/SubSubSpace/SomePage
to_adoc.sh SomePage.txt
----
Then just follow the prompts to_adoc.sh presents. You will be prompted before any publishing.
